### PR TITLE
Missing important chain (separator)

### PR DESCRIPTION
**Pull request by marcbria**
Reported here:
https://forum.pkp.sfu.ca/t/assign-evaluation-characters-appear-ojs-3-x/45721

@mtub this merge is important. Otherwise ojs will be defaced in Spanish.

### CODE REVIEW

**Comment by bozana** [comment]
i allowed myself to merge it...
thanks @marcbria!

**Comment by bozana** [comment]
@asmecher and @mtub, I am wondering if it would be better to add those two keys in every locale, then, if different in a language, it can be adjusted -- because earlier they were however hard coded. What do you think?

**Comment by marcbria** [comment]
I'm wondering why we missed this chain. :-/
If it was introduced between translations, Bozana's proposal is the most reasonable.
Do we have more chains like this?

OT: @mtub in our "wish list" for the perfect translation tool, we need to add a feature to help us tracking the new and the removable chains between versions.

**Comment by marcbria** [comment]
> @marcbria, may I maybe also add "common.semicolonListSeparator" as it is in en_US?

Yes please. Thanks Bozana.

**Comment by asmecher** [comment]
@bozana, yes, your proposal makes sense to me.

**Pull request merged**
