### PR TITLE
update es_ES translation in context

### PR DESCRIPTION
**Pull request by carzamora**
this line is not correct, @marcbria in this moment of the process the manuscript does not have reviewers, and the editors need to assign some reviewers.

If you prefer another sentence just tell me, and I can change it

### CODE REVIEW

**Comment by mtub** [comment]
@marcbria , what do you think?

**Comment by marcbria** [comment]
As usual, @carzamora is right. :+1: 
Thanks for the review of the translation in context...

**Comment by mtub** [comment]
Carlos, I know this PR is quite old, but do you mind signing the CLA (see above)? It is now required for all contributions to PKP code…

**Comment by carzamora** [comment]
no problem @mtub, is signed now?

**Comment by carzamora** [comment]
I do not understand why, but I signed three times and still as Pending

**Comment by carzamora** [comment]
I open a new PR because this was impossible to sign! I change my nick from t4x0n to carzamora, so I think this was the problem!  https://github.com/pkp/pkp-lib/pull/4127

**Comment by mtub** [comment]
superseded by #4127

**Pull request closed without merging**
