### PR TITLE
Relevant correction in italian locale

### PR DESCRIPTION
**Pull request by bolelligallevi**
This correction is important because the actual phrase "Notificami questo tipo di evento per email" means "Send me an email for these types of notifications.", that can lead to a wrong setting in the user profile

### CODE REVIEW

**Comment by asmecher** [comment]
@bolelligallevi, this can't be merged into the master branch because we have converted from XML to using PO files for our translations... Is this a change you're able to make?

**Comment by bolelligallevi** [comment]
@asmecher, I've never done it before, can you give me some clues to do it?

**Comment by asmecher** [comment]
Not to worry, @bolelligallevi, I've adapted it here: https://github.com/pkp/pkp-lib/commit/def6cc925092646b112a528ca9b9bcfb9754c5a7

**Comment by asmecher** [comment]
Thanks for contributing!

**Comment by bolelligallevi** [comment]
Thank you @asmecher

**Pull request closed without merging**
