### PR TITLE
Completed portuguese translations

### PR DESCRIPTION
**Pull request by ambs**
Thank you

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @ambs -- I've merged that into `stable-3_1_2`, but for the `master` branch (future 3.2.x releases) we're using Weblate for translations and have moved to the `.po` format. Have a look at https://pkp.sfu.ca/2020/01/22/introducing-weblate-a-new-path-for-ojs-omp-translations/.

**Comment by ambs** [comment]
@asmecher Are the current translations being used/converted, or the translation will be done from scratch? Just to prepare mentally for the task ;)
Cheers

**Comment by asmecher** [comment]
The translations that were in place when we launched the translation tools were converted to the new format, and there has been some progress on `pt_PT` using Weblate since then (see e.g. https://github.com/pkp/ojs/commit/26c486ec354bceddde8757293aa5d659d4b8e0ea). However, now that the two formats have diverged, it's tough to port changes made in one over to the other, so I'd recommend using the Weblate toolset as much as possible!

**Comment by ambs** [comment]
Yup, I understand. Will probably translate some more for this version, to have the site usable. As soon as 3.2 is out, and I update, I will help on finishing that. Thanks!

**Comment by asmecher** [comment]
Thanks, @ambs! If you have a lot of work done on a translation file, or some complete files that aren't yet translated in `master`, you can experiment with the `lib/pkp/tools/xmlToPo.php` tool in the 3.2.x codebase to convert `.xml` files to `.po` format.

**Pull request merged**
