### PR TITLE
pkp/pkp-lib#333, pkp/pkp-lib#2076: forward port Submission::getPageArray() to master.

### PR DESCRIPTION
**Pull request by ctgraham**
Helps to forward port pkp/pkp-lib#333 to master and provides foundation for resolving pkp/pkp-lib#2076.

Both issues still need application-specific pull requests for full resolution.

### CODE REVIEW

**Comment by bozana** [comment]
Thanks a lot @ctgraham!

**Comment by bozana** [comment]
Ah, the test is unfortunately not working in master :-( The Submission is abstract class there, so the object cannot be created.
Maybe we could either use the Application::getSubmissionDAO and then create the appropriate object (if ArticleDAO -> new Article(), if MonographDAO -> new Monograph()), or write another test class in each application, that would define $this->submission. @ctgraham, what do you think would be better?

**Comment by ctgraham** [comment]
Hmmm.... both approaches feel kind of awkward to me.  Who in our group has the most experience with unit testing to offer a recommendation?

**Comment by bozana** [comment]
maybe @asmecher :-)

**Comment by bozana** [comment]
I temporarily solved it, for tests not to fail, but when @asmecher suggests a good solution, I can change it again...

**Pull request merged**
