### PR TITLE
Update botAgents.txt

### PR DESCRIPTION
**Pull request by ajnyga**
Add two new bots that have begun appearing in the logs.

### CODE REVIEW

**Comment by ajnyga** [comment]
Especially BLEXBot seems to keep on loading the home page of some journals over and over again.

**Comment by asmecher** [comment]
@jmacgreg, any objections to adding these? (Asking because there may be ramifications for stats.)

**Comment by ajnyga** [comment]
Also: Feedbin

`159.65.xxx.xxx - - "2019-01-07 14:22:32" https://journal.fi/kasvatusjaaika/index 200 "Feedbin feed-id:21663 - 1 subscribers"`

See https://www.distilnetworks.com/bot-directory/bot/feedbin/

**Comment by jmacgreg** [comment]
Hi @ajnyga, @asmecher: rather than add these to our list like this, we should 

1) request that the COUNTER bot list, which is managed in [its own Github repo](https://github.com/atmire/COUNTER-Robots), include these (I don't see any of them there yet in the master list); 

2) make sure our bot list is synced reasonably frequently with the COUNTER bot list as source. 

I can take care of 1) right now (I'm in the bot list maintainers group) and I'll post an issue link when it's done here. @ajnyga, you should be able to support these changes locally for the time being. 

I'm not sure if our COUNTER bot list is updated automatically, either in a local OJS install over time, or at least as part of a release build - issue #3204 indicates to me that it's at least updated as a submodule, so it should be up to date on release of a new application version. @ajnyga, will this suffice going forward? @ctgraham, any additional thoughts on this?

**Comment by ajnyga** [comment]
Note that currently OJS uses both lists.

When data is entered to a log file OJS uses botAgents.txt, but when log files are processed into metrics it uses the COUNTER list. However, with the latter read my experiences from Slack.

**Comment by ajnyga** [comment]
Just fyi, that I am closing this.

The problem that was connected to this issue was elsewhere (https://github.com/pkp/pkp-lib/issues/4390). After the issue there got fixes SemrushBot and BLEXBot are being filtered using the COUNTER list.

However, the user agent "Feedbin feed-id:xxxxx - x subscribers" is still counted in the stats and is creating a lot of hits to the front page of a journal. 

I will suggest that the COUNTER list adds that agent.

**Comment by ajnyga** [comment]
fyi @jmacgreg : https://github.com/atmire/COUNTER-Robots/pull/20

**Comment by jmacgreg** [comment]
Thanks @ajnyga, I'll confirm with the COUNTER folks that the feedbin bot should be included. Thank you for your troubleshooting here!

**Pull request closed without merging**
