### PR TITLE
pkp/pkp-lib#2103 escape & in URL and interprete it correctly

### PR DESCRIPTION
**Pull request by bozana**
s. https://github.com/pkp/pkp-lib/issues/2103

### CODE REVIEW

**Comment by bozana** [comment]
I agree, but in the way it works now is also wrong :-(
Escaping "&" to "&amp;", as it was till now in classes/core/PKPRouter.inc.php, is not correct, I think. The URL will be separated by "&" and "amp;" will stay. 
Also, if an escaped URL is used, either with "&amp;" or "%26", OJS will not understand it, because _getUserVar will not be able to separate the variables.
Else, I agree that I am not sure about the extent of the change...

**Comment by ctgraham** [comment]
I think it depends on whether the $escape flag means "escape for HTML" (which I assume it does), or "encode the URL".  If outputting the URL to HTML or XML, the "&" to "&amp;" escaping is appropriate.
`<a href="http://my.url/path?var1=val1&amp;var2=val2">URL is http://my.url/path?var1=val1&amp;var2=val2</a>`
The URL encoding would only be appropriate if the "&" needed to be passed as a value, and not as part of the URL.
`<a href="http://my.url/redirect?action=302&amp;to=http%3A%2F%2Fmy.url%2Fpath%3Fvar1%3Dval1%26var2%3Dval2">URL is http://my.url/redirect?action=302&amp;to=http%3A%2F%2Fmy.url%2Fpath%3Fvar1%3Dval1%26var2%3Dval2</a>`

**Comment by bozana** [comment]
Yes, this could be -- that this "escape" means HTML escape. I thought it is an URL escape because if this parameter is true, the `%5B%5D` is used for `[ ]`, s. https://github.com/pkp/pkp-lib/blob/master/classes/core/PKPRouter.inc.php#L516.
OK, I will then close this PR and this issue and just fix the Crossref-URLs replacing the `[ ]` with `%5B%5D`. Also, we cannot use HTML encoding for URLs there, because it will be taken as it is and `&amp;` is not understood by OJS, thus `&` will stay there.

**Comment by bozana** [comment]
Ah, I forgot, we cannot use "&" in XML, thus it will have to be HTML escaped. I have no solution for this Crossref problem! :-(((

**Comment by ctgraham** [comment]
Isn't the problem CrossRef's itself?  We simply need to appropriately escape the URL for XML.  Interpreting that URL (or misinterpreting it) is on CrossRef.  There's no reason we shouldn't be able to provide a URL which contains square braces.

**Comment by bozana** [comment]
If we HTML/XML escape the URL, which we have to do, e.g. http://www.m-sciences.com/index.php?journal=ijas&amp;page=article&amp;op=view&amp;path%5B%5D=1076, that URL is apparently saved as it is by Crossref s. e.g. http://dx.doi.org/10.20454/ijas.2016.1076. And then OJS cannot interpret it. 
Thus, probably Crossref should decode those `&amp;` or?

**Comment by ctgraham** [comment]
Hmmm.... The [CrossRef (JSON) metadata](https://api.crossref.org/v1/works/http://dx.doi.org/10.20454/ijas.2016.1076) seems to have the ampersands encoded correctly.
```
{
   "status":"ok",
   "message-type":"work",
   "message-version":"1.0.0",
   "message":{
      "indexed":{
         "date-parts":[
            [
               2016,
               12,
               15
            ]
         ],
         "date-time":"2016-12-15T13:59:17Z",
         "timestamp":1481810357971
      },
      "reference-count":0,
      "publisher":"Modern Science Publishers",
      "issue":"2",
      "content-domain":{
         "domain":[

         ],
         "crossmark-restriction":false
      },
      "short-container-title":[
         "Int. J. of Algeb. and Stat."
      ],
      "abstract":"<jats:p>In this paper, \ufb01rst we de\ufb01ne the notions of translations and multiplications of doubt fuzzy BCK-submodules. Then we present some theorems which characterize the above notions. Also, we obtain some relationship between these notions and related properties are investigated.<\/jats:p>",
      "DOI":"10.20454\/ijas.2016.1076",
      "type":"journal-article",
      "created":{
         "date-parts":[
            [
               2016,
               12,
               15
            ]
         ],
         "date-time":"2016-12-15T10:13:28Z",
         "timestamp":1481796808000
      },
      "page":"67",
      "source":"CrossRef",
      "title":[
         " Action of translation in doubt fuzzy BCK-submodules"
      ],
      "prefix":"http:\/\/id.crossref.org\/prefix\/10.20454",
      "volume":"5",
      "author":[
         {
            "given":"A. S.",
            "family":"Al-lehyania",
            "affiliation":[

            ]
         }
      ],
      "member":"http:\/\/id.crossref.org\/member\/8371",
      "published-online":{
         "date-parts":[
            [
               2016,
               7,
               24
            ]
         ]
      },
      "container-title":[
         "International Journal of Algebra and Statistics"
      ],
      "original-title":[

      ],
      "link":[
         {
            "URL":"http:\/\/www.m-sciences.com\/index.php?journal=ijas&page=article&op=download&path%5B%5D=1076&path%5B%5D=1041",
            "content-type":"application\/pdf",
            "content-version":"vor",
            "intended-application":"text-mining"
         }
      ],
      "deposited":{
         "date-parts":[
            [
               2016,
               12,
               15
            ]
         ],
         "date-time":"2016-12-15T10:13:31Z",
         "timestamp":1481796811000
      },
      "score":1.0,
      "subtitle":[

      ],
      "short-title":[

      ],
      "issued":{
         "date-parts":[
            [
               2016,
               7,
               24
            ]
         ]
      },
      "URL":"http:\/\/dx.doi.org\/10.20454\/ijas.2016.1076",
      "ISSN":[
         "2314-4556",
         "2314-4548"
      ]
   }
}
```

The redirect coming from CrossRef, however, clearly has the ampersands encoded:
```
$ wget http://dx.doi.org/10.20454/ijas.2016.1076
--2016-12-16 10:16:30--  http://dx.doi.org/10.20454/ijas.2016.1076
Resolving dx.doi.org... 208.254.38.90, 54.191.229.235, 63.123.152.248, ...
Connecting to dx.doi.org|208.254.38.90|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.m-sciences.com/index.php?journal=ijas&amp;page=article&amp;op=view&amp;path%5B%5D=1076 [following]
```

Are we sure these weren't double encoded in the source XML?

**Comment by bozana** [comment]
First they were `&amp;amp;` but then I removed the second encoding and the user said he corrected it... If they are correctly in the JSON, then they are correct or?

**Comment by ctgraham** [comment]
I don't trust the JSON.  It is double-encoded in the XML:
```
curl -L  -iH "Accept: application/vnd.crossref.unixsd+xml" http://dx.doi.org/10.20454/ijas.2016.1076
HTTP/1.1 303 See Other
Server: Apache-Coyote/1.1
Vary: Accept
Location: http://data.crossref.org/10.20454%2Fijas.2016.1076
Expires: Fri, 16 Dec 2016 15:49:28 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 185
Date: Fri, 16 Dec 2016 15:40:14 GMT

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With, Accept, Accept-Encoding, Accept-Charset, Accept-Language, Accept-Ranges, Cache-Control
Access-Control-Expose-Headers: Link
Link: <http://dx.doi.org/10.20454/ijas.2016.1076>; rel="canonical", <http://www.m-sciences.com/index.php?journal=ijas&page=article&op=download&path%5B%5D=1076&path%5B%5D=1041>; version="vor"; type="application/pdf"; rel="item"
Content-Type: application/vnd.crossref.unixsd+xml
Content-Length: 4620
Server: http-kit
Date: Fri, 16 Dec 2016 15:40:14 GMT
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<crossref_result xmlns="http://www.crossref.org/qrschema/3.0" version="3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.crossref.org/qrschema/3.0 http://www.crossref.org/schemas/crossref_query_output3.0.xsd">
  <query_result>
    <head>
      <doi_batch_id>none</doi_batch_id>
    </head>
    <body>
      <query status="resolved">
        <doi type="journal_article">10.20454/ijas.2016.1076</doi>
        <crm-item name="publisher-name" type="string">Modern Science Publishers</crm-item>
        <crm-item name="prefix-name" type="string">Modern Science Publishers</crm-item>
        <crm-item name="member-id" type="number">8371</crm-item>
        <crm-item name="citation-id" type="number">86861170</crm-item>
        <crm-item name="journal-id" type="number">297509</crm-item>
        <crm-item name="deposit-timestamp" type="number">1481796592</crm-item>
        <crm-item name="owner-prefix" type="string">10.20454</crm-item>
        <crm-item name="last-update" type="date">2016-12-15T10:13:31Z</crm-item>
        <crm-item name="created" type="date">2016-12-15T10:13:28Z</crm-item>
        <crm-item name="citedby-count" type="number">0</crm-item>
        <doi_record>
          <crossref xmlns="http://www.crossref.org/xschema/1.1" xsi:schemaLocation="http://www.crossref.org/xschema/1.1 http://doi.crossref.org/schemas/unixref1.1.xsd">
            <journal>
              <journal_metadata>
                <full_title>International Journal of Algebra and Statistics</full_title>
                <abbrev_title>Int. J. of Algeb. and Stat.</abbrev_title>
                <issn media_type="electronic">2314-4556</issn>
                <issn media_type="print">2314-4548</issn>
              </journal_metadata>
              <journal_issue>
                <publication_date media_type="online">
                  <month>07</month>
                  <day>24</day>
                  <year>2016</year>
                </publication_date>
                <journal_volume>
                  <volume>5</volume>
                </journal_volume>
                <issue>2</issue>
              </journal_issue>
              <journal_article xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" publication_type="full_text" metadata_distribution_opts="any">
                <titles>
                  <title>Action of translation in doubt fuzzy BCK-submodules</title>
                </titles>
                <contributors>
                  <person_name contributor_role="author" sequence="first">
                    <given_name>A. S.</given_name>
                    <surname>Al-lehyania</surname>
                  </person_name>
                </contributors>
                <jats:abstract>
                  <jats:p>In this paper, ï¬rst we deï¬ne the notions of translations and multiplications of doubt fuzzy BCK-submodules. Then we present some theorems which characterize the above notions. Also, we obtain some relationship between these notions and related properties are investigated.</jats:p>
                </jats:abstract>
                <publication_date media_type="online">
                  <month>07</month>
                  <day>24</day>
                  <year>2016</year>
                </publication_date>
                <pages>
                  <first_page>67</first_page>
                  <other_pages>76</other_pages>
                </pages>
                <doi_data>
                  <doi>10.20454/ijas.2016.1076</doi>
                  <resource>http://www.m-sciences.com/index.php?journal=ijas&amp;amp;page=article&amp;amp;op=view&amp;amp;path%5B%5D=1076</resource>
                  <collection property="crawler-based">
                    <item crawler="iParadigms">
                      <resource>http://www.m-sciences.com/index.php?journal=ijas&amp;page=article&amp;op=download&amp;path%5B%5D=1076&amp;path%5B%5D=1041</resource>
                    </item>
                  </collection>
                  <collection property="text-mining">
                    <item>
                      <resource mime_type="application/pdf">http://www.m-sciences.com/index.php?journal=ijas&amp;page=article&amp;op=download&amp;path%5B%5D=1076&amp;path%5B%5D=1041</resource>
                    </item>
                  </collection>
                </doi_data>
              </journal_article>
            </journal>
          </crossref>
        </doi_record>
      </query>
    </body>
  </query_result>
</crossref_result>
```

**Comment by ctgraham** [comment]
But note, it is only double encoded in the actual `//doi_data/resource` link!  `//doi_data/collection/resource` links are OK!

**Comment by bozana** [comment]
Hmmm... OK, that would probably mean, that the user didn't apply all the changes :-(((
Thanks a lot for your help!!!

**Pull request closed without merging**
