### PR TITLE
pkp/pkp-lib#5588 Fix missing fetch for submission locale via AuthorDAO

### PR DESCRIPTION
**Pull request by asmecher**

### CODE REVIEW

**Comment by asmecher** [comment]
@NateWr, could you have a look at this? The move to SchemaDAO resulted in the loss of the submission's `locale` column, which was [fetched in the PKPAuthorDAO implementation prior to 3.2.x](https://github.com/pkp/pkp-lib/blob/stable-3_1_2/classes/submission/PKPAuthorDAO.inc.php#L31).

My solution for now is to override `SchemaDAO`'s implementation of `getById` and `_fromRow` to add the fetch/column. That's safest/best for 3.2.0-x and 3.2.1, I think, but for 3.3 and onwards this might be a good candidate for experimentation with the ephemeral Stash driver as discussed at https://github.com/pkp/pkp-lib/issues/3304#issuecomment-615453202. Rather than denormalizing the fetch, we could add the ephemeral driver to the `SubmissionDAO` and `PublicationDAO` (or better yet, underlying `SchemaDAO`) and the author fetch could simply get the whole publication objet, relying on caching to keep it efficient.

**Comment by NateWr** [comment]
That looks good. I've been doing this entirely in the `_fromRow()` method, such as [getting controlled vocabulary](https://github.com/pkp/pkp-lib/blob/master/classes/publication/PKPPublicationDAO.inc.php#L48-L77). I appreciate that involves an extra database query rather than a join, but I think it's the least intrusive way. 

Since `_fromRow()` is often going to be extended, but `getById()` probably isn't, I think it's less likely to introduce an unusual situation. For example, if we added a hook to `SchemaDAO::getById()` we probably wouldn't remember to call it in `Author::getById()`.

But again I appreciate from a performance perspective it's maybe a worse solution since it requires extra calls to the database. I think, as you describe, using a cached record in `_fromRow()` is probably best. But I'd like to see this call `Services::get('publication')->get($id)` rather than calling the DAO directly, although I know that the `get()` method on entity service classes is just a wrapper for the DAO so far.

**Comment by quartelmestre** [comment]
@asmecher , I applied this patch to my installation, and it didn't work. Furthermore, per the PHP log:

> NOTICE: PHP message: PHP Notice:  Undefined index: submission_locale in /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/submission/PKPAuthorDAO.inc.php on line 144

**Comment by asmecher** [comment]
@quartelmestre, maybe you could help me identify excactly what's happening there?
- In your `config.inc.php`, turn on `show_stacktrace`
- In your `PKPAuthorDAO.inc.php` class, in the `_fromRow` function, add at the beginning of the function:
  ```
  if (!isset($primaryRow['submission_locale'])) fatalError('Unset submission_locale!');
  ```
- Go to whatever page seems to be causing the warning and load it again; this time it should generate a stack trace in your PHP log.

You might want to make the modification only briefly to `PKPAuthorDAO.inc.php` if your site is in production, as it'll turn a warning into an error.

Provide the stack trace here and it'll give me more information about the use case that's not behaving as expected.

**Comment by asmecher** [comment]
@NateWr,
> I've been doing this entirely in the _fromRow() method, such as getting controlled vocabulary. I appreciate that involves an extra database query rather than a join, but I think it's the least intrusive way.

These kinds of queries are probably going to need optimization, as they can multiply out by entity (e.g. Submissions fetching Publications fetching Authors, Controlled Vocabularies, etc) and are frequent operations on the front end where the highest user volume is seen. I'm thinking of two strategies:
1. Denormalizing fetches where cardinalities suit, like this example. I agree that overriding `getById` will cause some pain. I think we can circumvent that by going with QueryBuilder tools, and allowing the subclass to augment the query rather than reimplementing it.
2. Object caching. I've got a working experiment that adds caching to anything extending SchemaDAO (both with the Ephemeral and Memcache drivers) at https://github.com/pkp/pkp-lib/pull/5743 and it's looking pretty promising.

I think we can pursue both approaches in tandem, i.e. no need to pick one over the other. The first is a little more surgical.

**Comment by quartelmestre** [comment]
@asmecher , here is the stack trace:

Unset submission_locale!
Stack Trace:
File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 108
Function: PKPAuthorDAO->_fromRow(Array(7), Array(0))
Unset submission_locale!
Stack Trace:
File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 108
Function: PKPAuthorDAO->_fromRow(Array(7), Array(0))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultIterator.inc.php line 33
Function: DAOResultFactory->next()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 231
Function: DAOResultIterator->__construct(Object(DAOResultFactory))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/services/PKPAuthorService.inc.php line 69
Function: DAOResultFactory->toIterator()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/publication/PKPPublicationDAO.inc.php line 53
Function: PKP\Services\PKPAuthorService->getMany(Array(1))

File: /usr/local/apache2/htdocs/gradusjournal.com/classes/publication/PublicationDAO.inc.php line 40
Function: PKPPublicationDAO->_fromRow(Array(12))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 108
Function: PublicationDAO->_fromRow(Array(12), Array(0))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultIterator.inc.php line 33
Function: DAOResultFactory->next()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 231
Function: DAOResultIterator->__construct(Object(DAOResultFactory))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/services/PKPPublicationService.inc.php line 80
Function: DAOResultFactory->toIterator()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/submission/PKPSubmissionDAO.inc.php line 91
Function: PKP\Services\PKPPublicationService->getMany(Array(1))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 108
Function: PKPSubmissionDAO->_fromRow(Array(12), Array(0))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultIterator.inc.php line 33
Function: DAOResultFactory->next()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 231
Function: DAOResultIterator->__construct(Object(DAOResultFactory))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/services/PKPSubmissionService.inc.php line 106
Function: DAOResultFactory->toIterator()

File: /usr/local/apache2/htdocs/gradusjournal.com/pages/issue/IssueHandler.inc.php line 313
Function: PKP\Services\PKPSubmissionService->getMany(Array(5))

File: /usr/local/apache2/htdocs/gradusjournal.com/pages/issue/IssueHandler.inc.php line 104
Function: IssueHandler::_setupIssueTemplate(Object(Request), Object(Issue), False)

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/core/PKPRouter.inc.php line 391
Function: IssueHandler->view(Array(1), Object(Request))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/core/PKPPageRouter.inc.php line 231
Function: PKPRouter->_authorizeInitializeAndCallRequest(Array(2), Object(Request), Array(1), False)

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/core/Dispatcher.inc.php line 143
Function: PKPPageRouter->route(Object(Request))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/core/PKPApplication.inc.php line 278
Function: Dispatcher->dispatch(Object(Request))

File: /usr/local/apache2/htdocs/gradusjournal.com/index.php line 69
Function: PKPApplication->execute()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultIterator.inc.php line 33
Function: DAOResultFactory->next()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 231
Function: DAOResultIterator->__construct(Object(DAOResultFactory))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/services/PKPAuthorService.inc.php line 69
Function: DAOResultFactory->toIterator()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/publication/PKPPublicationDAO.inc.php line 53
Function: PKP\Services\PKPAuthorService->getMany(Array(1))

File: /usr/local/apache2/htdocs/gradusjournal.com/classes/publication/PublicationDAO.inc.php line 40
Function: PKPPublicationDAO->_fromRow(Array(12))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 108
Function: PublicationDAO->_fromRow(Array(12), Array(0))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultIterator.inc.php line 33
Function: DAOResultFactory->next()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 231
Function: DAOResultIterator->__construct(Object(DAOResultFactory))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/services/PKPPublicationService.inc.php line 80
Function: DAOResultFactory->toIterator()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/submission/PKPSubmissionDAO.inc.php line 91
Function: PKP\Services\PKPPublicationService->getMany(Array(1))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 108
Function: PKPSubmissionDAO->_fromRow(Array(12), Array(0))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultIterator.inc.php line 33
Function: DAOResultFactory->next()

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/db/DAOResultFactory.inc.php line 231
Function: DAOResultIterator->__construct(Object(DAOResultFactory))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/services/PKPSubmissionService.inc.php line 106
Function: DAOResultFactory->toIterator()

File: /usr/local/apache2/htdocs/gradusjournal.com/pages/issue/IssueHandler.inc.php line 313
Function: PKP\Services\PKPSubmissionService->getMany(Array(5))

File: /usr/local/apache2/htdocs/gradusjournal.com/pages/issue/IssueHandler.inc.php line 104
Function: IssueHandler::_setupIssueTemplate(Object(Request), Object(Issue), False)

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/core/PKPRouter.inc.php line 391
Function: IssueHandler->view(Array(1), Object(Request))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/core/PKPPageRouter.inc.php line 231
Function: PKPRouter->_authorizeInitializeAndCallRequest(Array(2), Object(Request), Array(1), False)

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/core/Dispatcher.inc.php line 143
Function: PKPPageRouter->route(Object(Request))

File: /usr/local/apache2/htdocs/gradusjournal.com/lib/pkp/classes/core/PKPApplication.inc.php line 278
Function: Dispatcher->dispatch(Object(Request))

File: /usr/local/apache2/htdocs/gradusjournal.com/index.php line 69
Function: PKPApplication->execute()

**Comment by asmecher** [comment]
Thanks, that helps, @quartelmestre! I've added an additional commit to this PR that should resolve it:
https://github.com/pkp/pkp-lib/pull/5805/commits/db438d7e8a71d094c76d81fa7b07c8511f3363ec
Please confirm when you have a moment?

**Comment by quartelmestre** [comment]
@asmecher , it worked. No error message about submission_locale in the logs, and the authors' names are shown in all languages. Thank you very much!

**Comment by asmecher** [comment]
Excellent -- thanks for the confirmation, @quartelmestre! I'll get this merged and released in OJS/OMP/OPS 3.2.0-3 --  possibly today.

**Pull request merged**
