### PR TITLE
Update submission.po

### PR DESCRIPTION
**Pull request by alexxxmendonca**
Fixed mistake in "licensiado" (correct: licenciado)

### CODE REVIEW

**Comment by asmecher** [comment]
Merged and cherry-picked -- but can these changes be done through Weblate? Merging them via github directly requires bit more management.

**Comment by alexxxmendonca** [comment]
Hi @asmecher I couldn't find them on weblate, Reason why I did here.
Could you point me where to find them?

**Comment by asmecher** [comment]
You could find these e.g. by searching for ` source:submission.license.cc Creative Commons` in the form at https://translate.pkp.sfu.ca/projects/pkp-lib/submission/#search

**Comment by alexxxmendonca** [comment]
@asmecher how do I know that?

It's not clear to me what I have to search for.

I have the string that is mistaken. If I search for the string that is currently available on production, shouldn't that work:?

**Comment by asmecher** [comment]
Have a look at https://docs.weblate.org/en/weblate-3.9.1/user/search.html for information on the search form syntax.

The `language:es_ES` restricts search results to Spanish; I just picked "Creative Commons" as relatively unique words that appeared in the text. You could also search by locale key using:
```
language:es_ES "submission.license.cc.by-nc4.footer"
```
If you're not sure what file/project you need to look in, you can also perform a global search at https://translate.pkp.sfu.ca/#search

**Comment by alexxxmendonca** [comment]
Thank you @asmecher !

If a similar issue occurs again, I'll follow these instructions.

**Pull request merged**
