### PR TITLE
Change input type from text to tel

### PR DESCRIPTION
**Pull request by Mandroide**

### CODE REVIEW

**Comment by Mandroide** [comment]
@thinkbulecount2 What do you think? Is it anything missing?

**Comment by thinkbulecount2** [comment]
Hi @Mandroide! Sorry for the delay, this got lost in my emails but I also saw your [other PR](https://github.com/pkp/ojs/pull/2757) and they both look good to me!

**Comment by Mandroide** [comment]
> Hi @Mandroide! Sorry for the delay, this got lost in my emails but I also saw your [other PR](https://github.com/pkp/ojs/pull/2757) and they both look good to me!

I saw that there was another outside of the pkp-lib, so I made that PR for OJS all in one.

**Comment by thinkbulecount2** [comment]
Just doing some testing on my end, and waiting for the automatic tests to finish as well before I ping @NateWr to do a final review and merge. :)

**Pull request closed without merging**
