### PR TITLE
Update ModalHandler.js

### PR DESCRIPTION
**Pull request by djolemc**
Fixes bug on modals that don't have title. Instead of undefined, displays only empty div header. For example, on submission > activity log & notes modal.

### CODE REVIEW

**Comment by asmecher** [comment]
@djolemc, can you add a description here to say what the proposed change adds/corrects? Thanks!

**Comment by djolemc** [comment]
> @djolemc, can you add a description here to say what the proposed change adds/corrects? Thanks!

Updated...

**Comment by asmecher** [comment]
Thanks, @djolemc! One small change to request: instead of indenting with spaces, could you indent with tabs?

**Comment by djolemc** [comment]
Should be better now...

**Comment by asmecher** [comment]
That's perfect -- thanks, @djolemc! I'll port around as necessary.

**Pull request merged**
