### PR TITLE
pkp/pkp-lib#602 Style tag-it form components

### PR DESCRIPTION
**Pull request by NateWr**
This PR just styles the tag-it form components. We still have problems with the data being saved under Submission > Metadata. Also, the autocomplete function seems to be querying a 404:

```
GET http://192.168.0.8/ojs/index.php/publicknowledge/submission/fetchChoices?codeList=74&term=English&_=1438859427803 404 (Not Found)jQuery.ajaxTransport.send @ jquery.js:9666jQuery.extend.ajax @ jquery.js:9211$.tagit.tagSource @ VM18654:8jQuery.extend.proxy.proxy @ jquery.js:556$.widget._search @ jquery-ui.js:3122(anonymous function) @ jquery-ui.js:407$.widget.search @ jquery-ui.js:3114(anonymous function) @ jquery-ui.js:407(anonymous function) @ jquery-ui.js:3095handlerProxy @ jquery-ui.js:744
jquery.js:9666 XHR finished loading: GET "http://192.168.0.8/ojs/index.php/publicknowledge/submission/fetchChoices?codeList=74&term=English&_=1438859427803".
```

I'm going to take a quick crack at this. But I doubt I'll find the solution quickly so will probably just move on. If I find anything I'll push into this branch, probably before you wake up.

### CODE REVIEW

**Comment by NateWr** [comment]
I did a bit of digging into why submission metadata in tag-it components doesn't save but ran into a bit of a wall and so I'm moving on.

Saving notes for the next person (or myself later):

`submissionMetadataFormFields.tpl` loads these fields with locale prefixes for multilingual sites:

```
		{fbvElement type="keyword" id="languages" subLabelTranslate=true multilingual=true current=$languages source=$languagesSourceUrl disabled=$readOnly}
```

This prepends the locale to the hidden `input` field names for each language:

```
<input type="hidden" value="English" name="en_US-languages" class="tagit-hidden-field">
```

This gets serialized into a string one might generate with a `GET` request, then this string is **posted** to the URL:

```
submissionId=2&stageId=3&displayedInContainer=1&tab=submission&sectionId=1&prefix%5Ben_US%5D=&title%5Ben_US%5D=The+influence+of+lactation+on+the+quantity+and+quality+of+cashmere+production&subtitle%5Ben_US%5D=&abstract%5Ben_US%5D=%3Cp%3EAn+abstract%3C%2Fp%3E&coverageChron%5Ben_US%5D=&coverageGeo%5Ben_US%5D=&coverageSample%5Ben_US%5D=&type%5Ben_US%5D=&subjectClass%5Ben_US%5D=&source%5Ben_US%5D=&rights%5Ben_US%5D=&en_US-languages=English&en_US-languages=French&citations=
```

I got lost trying to figure out where this data is handled in the backend. But the problem is probably there, not with the tag-it components themselves. (The tag-it component does work for reviewing interests.)

**Comment by asmecher** [comment]
@jnugent or @beghelli, are either of you up for this one?

**Comment by asmecher** [comment]
(see also https://github.com/pkp/ojs/pull/556)

**Comment by asmecher** [comment]
Merged manually --there was a conflict. See:
https://github.com/pkp/pkp-lib/commit/dc6e2b909995e100acf53c77850f5ce968607eff
https://github.com/pkp/pkp-lib/commit/64e048883557f1ee8262e6436016a1d08ef2788d

**Pull request closed without merging**
