### PR TITLE
PKPRequest::getServerHost() enchanced to deal with multiple host names in a host header.

### PR DESCRIPTION
**Pull request by zozlak**
Depending on the reverse proxy configuration every reverse proxy may append its host name to the HTTP_X_FORWARDED_HOST instead of replacing it (this is e.g. a default Apache behaviour).

In such a case the final header value is a (comma-delimited) list of server names with the original request server name in front, e.g. `clarin.oeaw.ac.at, tokeneditor.apollo.arz.oeaw.ac.at` and the right way to process it is to split it into single host names and take the first value.

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @zozlak, that seems sensible -- but can you convert the space-based indents to tabs for consistency with the rest of the codebase?

**Comment by zozlak** [comment]
Done

**Comment by asmecher** [comment]
Thanks -- merged and back-ported to `stable-3_1_2` for the next release from that branch!

**Comment by asmecher** [comment]
This caused test failures -- I adjusted the implementation to rely less on array operations: https://github.com/pkp/pkp-lib/commit/778b738fce3d5dcc50d915db7656ecd62f8f6a94

**Pull request merged**
