### PR TITLE
Add sender_id and event_type to logged REVISED_VERSION_NOTIFY messages

### PR DESCRIPTION
**Pull request by ajnyga**
See https://github.com/pkp/pkp-lib/issues/4070

### CODE REVIEW

**Comment by asmecher** [comment]
Looks good, @ajnyga. Have you looked over the CLA yet? There's a plain-text description we recently added here: https://pkp.sfu.ca/contributor-license-agreement/

**Comment by ajnyga** [comment]
Ping @asmecher CLA is signed.

**Comment by ajnyga** [comment]
Hi @asmecher, planning to do some work related to this pr (need to have the event_type in the db for these messages). No rush with merging, but can you confirm that the code itself is ok? Just want to make sure I do not work on something that ends up being useless...

**Comment by asmecher** [comment]
Merged -- thanks, @ajnyga!

**Pull request merged**
