### PR TITLE
Change input type from text to search

### PR DESCRIPTION
**Pull request by Mandroide**

### CODE REVIEW

**Comment by thinkbulecount2** [comment]
Hi again @Mandroide! Found that this also occurs in OJS:
`/ojs/templates/controllers/grid/pubIds/pubIdExportRepresentationsGridFilter.tpl`
`/ojs/templates/controllers/grid/submissions/exportPublishedSubmissionsGridFilter.tpl`
`/ojs/templates/controllers/grid/subscriptions/subscriptionsGridFilter.tpl`

Would you like to do the change or should I?

Thank you!!!

**Comment by Mandroide** [comment]
> Hi again @Mandroide! Found that this also occurs in OJS:
> `/ojs/templates/controllers/grid/pubIds/pubIdExportRepresentationsGridFilter.tpl`
> `/ojs/templates/controllers/grid/submissions/exportPublishedSubmissionsGridFilter.tpl`
> `/ojs/templates/controllers/grid/subscriptions/subscriptionsGridFilter.tpl`
> 
> Would you like to do the change or should I?
Done. Thanks.

**Comment by asmecher** [comment]
> Done. Thanks.

The PR for this is at: https://github.com/pkp/ojs/pull/2721

**Comment by thinkbulecount2** [comment]
Form builder vocabulary needed to be extended to include `type="search"` (found in `classes/form/FormBuilderVocabulary.inc.php`)

Also added `search` (as `FBV_isTypeSearch`) as a parameter in `templates/form/textInput.tpl`.

For your review, @NateWr!

**Comment by NateWr** [comment]
@Mandroide can you pull this commit into your branch? https://github.com/thinkbulecount2/pkp-lib/commit/897dda2b8d4a3960f275e1a54cb8404e01d458c3 Then I can merge the whole lot. If you're not sure how, let me know and I can put together a new PR.

**Comment by Mandroide** [comment]
> @Mandroide can you pull this commit into your branch? [thinkbulecount2@897dda2](https://github.com/thinkbulecount2/pkp-lib/commit/897dda2b8d4a3960f275e1a54cb8404e01d458c3) Then I can merge the whole lot. If you're not sure how, let me know and I can put together a new PR.

Done. I think it would be better to rebase it onto master instead of merging it to avoid creating an unnecesary commit that doesn't introduce changes to the tree.

**Comment by NateWr** [comment]
Great, thanks @Mandroide! I realize looking back over this that we have OJS commits as well. There's just one more thing we need to do to ensure the tests get run properly for OJS. 

In order to link the pkp-lib and ojs changes together, so that tests get run on the correct set of commits, we use a special commit. You can add that in your OJS repo like this:

```
cd <ojs-root>
git checkout feature-input-search
cd lib/pkp
git checkout feature-search-form
git add lib/pkp
git commit -m "Submodule update ##Mandroide/feature-search-form##"
git push
```

That will kick off the tests again over at https://github.com/pkp/ojs/pull/2721 only this time when running the tests Travis will ensure the correct branch of pkp-lib is checked out.

Once those tests have passed drop me a note and I can merge both. Thanks again!

**Comment by Mandroide** [comment]
> Great, thanks @Mandroide! I realize looking back over this that we have OJS commits as well. There's just one more thing we need to do to ensure the tests get run properly for OJS.
> 
> In order to link the pkp-lib and ojs changes together, so that tests get run on the correct set of commits, we use a special commit. You can add that in your OJS repo like this:
> 
> ```
> cd <ojs-root>
> git checkout feature-input-search
> cd lib/pkp
> git checkout feature-search-form
> git add lib/pkp
> git commit -m "Submodule update ##Mandroide/feature-search-form##"
> git push
> ```
> 
> That will kick off the tests again over at [pkp/ojs#2721](https://github.com/pkp/ojs/pull/2721) only this time when running the tests Travis will ensure the correct branch of pkp-lib is checked out.
> 
> Once those tests have passed drop me a note and I can merge both. Thanks again!
> 
Done. Also, if you've got time, you might want to add [this](https://github.com/pkp/ojs/pull/2714) to _ojs_ as well.

**Pull request merged**
