### PR TITLE
add HasCamelCasing trait to UserGroupStage, UserUserGroup, and  InvitationModel models

### PR DESCRIPTION
**Pull request by taslangraham**
For #10234

### CODE REVIEW

**Comment by taslangraham** [comment]
Ready for review @asmecher

**Comment by asmecher** [comment]
Thanks, @taslangraham! @defstat, would you mind reviewing this?

**Comment by defstat** [comment]
@taslangraham thanks, this trait saves so much code and it is super helpful. Can you add the necessary PRs on OJS, OMP, OPS so that the tests run on the pkp-lib PR?

**Comment by defstat** [comment]
If you need any help with the tests I will be happy to help.

**Comment by taslangraham** [comment]
@defstat I've added a pr for submodule updates for each app. 
I've listed them here in the issue description - https://github.com/pkp/pkp-lib/issues/10234

**Review by defstat — CHANGES_REQUESTED** [review]
Thanks @taslangraham. Just check one test that has already failed on OMP. It could be a test glitch and could be resolved if you rerun it. But check if this is the case. Other than that I have no comments on the code

**Comment by taslangraham** [comment]
@defstat all tests are now passing.

**Comment by defstat** [comment]
Perfect, I have no other comments

**Comment by taslangraham** [comment]
@defstat I don't have write access. If you do, could you please merge this?

**Comment by defstat** [comment]
@taslangraham everything merged! Thanks.

**Pull request merged**
