### PR TITLE
pkp/pkp-lib#4133 fix comparison of datetime

### PR DESCRIPTION
**Pull request by ajnyga**
ping @asmecher

### CODE REVIEW

**Comment by asmecher** [comment]
Call me pedantic :) but I'd rather not do string operations on dates. I'd prefer something like this, even though it's longer... (needs testing!)

    $dueDate = strtotime($reviewAssignment->getDateDue());
    $reviewDueDate = strtotime($this->getData('reviewDueDate'));
    if (date('Y-m-d', $dueDate) != date('Y-m-d', $reviewDueDate)) {
        ...

One thing I'd **really** love to do after @NateWr has merged his form changes is standardize date handling -- the current mix of strings and numerics is maddening!

**Comment by ajnyga** [comment]
You already have that in OJS in several places. I mean that substr used against those same values.

**Comment by ajnyga** [comment]
This seems to work as well, would it be ok?

`strtotime($reviewAssignment->getDateDue()) != strtotime($this->getData('reviewDueDate'))`

`strtotime('2018-02-02 00:00:00')` and  `strtotime('2018-02-02')` return the same timestamp.

**Comment by asmecher** [comment]
Yes, I think that would work. (Our date/time code is not particularly clean or consistent -- I'd like to get that cleaned up at some point!)

**Comment by ajnyga** [comment]
changed

**Pull request merged**
