### PR TITLE
pkp/pkp-lib#1505 german translations ##henkela/master##

### PR DESCRIPTION
**Pull request by henkela**
Finally, a commit from a seperate clone of pkp-lib

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @henkela! @mtub, this one goes with https://github.com/pkp/ojs/pull/856.

**Comment by henkela** [comment]
@asmecher,@mtub I think it should now rather go with #857 because of my "start from the beginning"

**Comment by asmecher** [comment]
Thanks, I see that now! Closed https://github.com/pkp/ojs/pull/856 now that https://github.com/pkp/ojs/pull/857 is preferred.

**Comment by mtub** [comment]
Closing, superseded by latest de_DE locale updates (which have been compared to/cross-checked with the suggestions in these PRs)

**Pull request closed without merging**
