### PR TITLE
Update German translation (issue #2972)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by dennmuel** [comment]
The English text was negated three years ago ([11c07ae](https://github.com/pkp/pkp-lib/commit/11c07aeacf5b814c1f3c6c429d62ab73d9eb7312)). Might well be other locales haven't been updated.
See the respective line in the English locale [here](https://github.com/pkp/pkp-lib/blob/2d3a99b488249361b254036ecfcc40fbd9f4b018/locale/en_US/common.xml#L443).

Maybe just "für diese Arten von Benachrichtigungen"? But honestly I think that users will get it one way or another as long as the checkbock says what it does and does what it says. :)

**Comment by stweil** [comment]
Thanks for investigating that issue. I think the commit which negated the text without renaming the key was not a good idea. I strongly suggest to rename the key from "notification.email" to "notification.noEmail" and would add a commit which does that as soon as the project maintainers agree.

**Comment by mtub** [comment]
I agree that the initial renaming was not a very good thing to do, and it seems as if almost every other locale still has this wrong. Changes like these should be done by introducing a new key.

Waiting for @asmecher to decide on where to go from here regarding the wrong locale keys for notification.Email. Okay with the other changes in this PR.

**Comment by stweil** [comment]
@asmecher, I suggest to merge this PR first then before going on with renaming of the key.

**Comment by asmecher** [comment]
Thanks, @stweil and @mtub. I agree that negating the locale key was a bad choice here -- in the future the key should be renamed, and existing translations should be adapted (when confident about the language) and removed when not. I've merged this PR, and removed incorrect locales, updating the ones that I'm confident about.

**Pull request merged**
