### PR TITLE
Update fr ca locale

### PR DESCRIPTION
**Pull request by pnault**
Hi,

The last commit is the good one. Forget the one made on April 11.

### CODE REVIEW

**Comment by asmecher** [comment]
@pnault, I can't merge just the one commit and there's now a merge conflict. The way to fix that so it can be merged is to do a rebase and resolve any conflicts. Are you comfortable enough with git to do that?

**Comment by pnault** [comment]
Mmm I'm not sure to understand: these are not the same files.
I have a local repo (windows) and the one on Github. On my local repo and in Gitshell I have done:
git rebase --interactive and in the file appearing there seems to be no commits.

Any help would be appreciated

**Comment by asmecher** [comment]
@pnault, working with git remotely is a challenge :) but I suspect you need to...

1) fetch the latest version of the official repository, then
2) specify what you're rebasing against when running your rebase:
  `git rebase -i official/master`
  (where `official` would be the name of the official PKP`pkp-lib` remote)

**Comment by pnault** [comment]
if you don't mind answering dumb questions...

My Git environment is set following this document: https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors

so my origin/master is on my remote repo. I did in shell:
```
$~/Desktop/ftp-dump/github/pkp-lib (master)
$git checkout master
$git fetch origin
$ git status
Your branch is up-to-date with 'origin/master'.
```
fetching like this doesn't update my local repo it does just synchronize it with my official/master on my repo righ?

**Comment by asmecher** [comment]
Do you have an `official` remote set up? You can check as follows:

```
$ git remote -v | grep official
official	git@github.com:pkp/pkp-lib.git (fetch)
official	git@github.com:pkp/pkp-lib.git (push)
```
As you see, my setup does have one. If you don't, you'll need to use `git remote add ...` to add it.

Then, once you've got it listed, you can fetch the latest from it using

```
git fetch official
```

Then you can rebase on top of it to resolve the merge conflict.

**Comment by pnault** [comment]
I think that I have solve the merge conflict.
But not sure that my local repo is OK:
```
~/Desktop/ftp-dump/github/pkp-lib (update-fr-ca-locale)
$ git status
On branch update-fr-ca-locale
Your branch and 'origin/update-fr-ca-locale' have diverged,
and have 369 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        locale/fr_CA/common.xml.bak
        locale/fr_CA/reviewer.xml.bak
        peegoo1e.dxi.txt
```

**Comment by asmecher** [comment]
@pnault, it looks like it worked -- I've merged it, thanks!

**Pull request merged**
