### PR TITLE
Change input type from text to email

### PR DESCRIPTION
**Pull request by Mandroide**
Ease in user experience

### CODE REVIEW

**Comment by Mandroide** [comment]
I also see some template and less files that might need to be change the types from _text_ to _tel_ and _email_

**Comment by thinkbulecount2** [comment]
Hi! Do we want to add some basic email validation? For example in [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#Validation).

**Comment by NateWr** [comment]
@thinkbulecount2 I think browsers do this automatically for `type="email"`. From the MDN link:

> Browsers that support the email input type automatically provide validation to ensure that only text that matches the standard format for Internet e-mail addresses is entered into the input box.

**Comment by thinkbulecount2** [comment]
Thanks @NateWr I missed that part.

**Comment by NateWr** [comment]
Seems like a sensible change to me and the default theme stylesheets already support the different types: https://github.com/pkp/ojs/blob/master/plugins/themes/default/styles/components.less#L199-L214.

@thinkbulecount2 do you have any objections to merge here?

**Comment by thinkbulecount2** [comment]
Just doing some digging, would these need changes too, @NateWr?

https://github.com/pkp/pkp-lib/blob/73a00692e0042783e90c8e5e89aab8c03424e743/templates/common/userDetails.tpl#L50

`{if !$disableEmailSection}
  	{fbvFormSection title="about.contact"}
 		{fbvElement type="text" label="user.email" id="email" required="true" value=$email maxlength="90" size=$fbvStyles.size.MEDIUM}
  	{/fbvFormSection}
{/if}`

And similar here:
https://github.com/pkp/pkp-lib/blob/73a00692e0042783e90c8e5e89aab8c03424e743/templates/user/contactForm.tpl#L26

**Comment by Mandroide** [comment]
> Seems like a sensible change to me and the default theme stylesheets already support the different types: https://github.com/pkp/ojs/blob/master/plugins/themes/default/styles/components.less#L199-L214.
> 
> @thinkbulecount2 do you have any objections to merge here?

I didn't notice inside the default stylesheet it's been calling "_input[type="phone"]_" when the type is really _input[type="tel"]_. Just a small spot. 👌

**Comment by NateWr** [comment]
@thinkbulecount2 yep, those would be good places to change as well.

@Mandroide good spot! Are you willing to add this change and the ones that @thinkbulecount2 into this PR?

**Comment by Mandroide** [comment]
> @thinkbulecount2 yep, those would be good places to change as well.
> 
> @Mandroide good spot! Are you willing to add this change and the ones that @thinkbulecount2 into this PR?

Alright! This PR is done.

**Comment by thinkbulecount2** [comment]
Looks good to me! @NateWr

**Comment by NateWr** [comment]
Thanks everyone!

**Pull request merged**
