### PR TITLE
pkp/pkp-lib#1039 Fix 4ba8a22 - Show announcements at the published date

### PR DESCRIPTION
**Pull request by lepidus**
Fix previous PR regarding issue pkp/pkp-lib#1039

### CODE REVIEW

**Comment by asmecher** [comment]
This still affects the behavior of the expiry; is that intentional?

**Comment by mfelczak** [comment]
@asmecher, both checks ultimately need the inclusion of the DATE() call to work correctly, so maybe this issue needs to be reworded to reflect that.

**Comment by asmecher** [comment]
Thanks, @mfelczak -- I did that. The query also checks out for PostgreSQL. Ready to merge from your perspective?

**Comment by mfelczak** [comment]
Yep, looks good.

**Comment by asmecher** [comment]
Merged, thanks!

**Pull request merged**
