### PR TITLE
Ojs stable 3 0 1

### PR DESCRIPTION
**Pull request by Vitaliy-1**

### CODE REVIEW

**Comment by asmecher** [comment]
@Vitaliy-1, this looks like it contains a lot of commits that shouldn't be there -- perhaps you're opening the pull request against the wrong branch?

**Comment by Vitaliy-1** [comment]
Wrong action. Just delete it. I need additional info how to commit. I have done it from only from console to my own projects

**Comment by Vitaliy-1** [comment]
Can I somehow сancel this action?

**Comment by asmecher** [comment]
No problem, I'll close it.

**Pull request closed without merging**
