### PR TITLE
pkp/pkp-lib#9310 consider all accept decisions for editorial stats

### PR DESCRIPTION
**Pull request by bozana**
s. https://github.com/pkp/pkp-lib/issues/9310

### CODE REVIEW

**Review by jonasraoni — CHANGES_REQUESTED** [review]
I think the update makes sense. But if you drill down inside the `countByDecisions()`, you'll reach a place where there's a left join with the `edit_decisions` table, that might fail (when there's a `dateStart`/`dateEnd`):
https://github.com/pkp/pkp-lib/blob/ddb2d5f0f64726dff1ecba65c0b30210bce4359c/classes/services/queryBuilders/PKPStatsEditorialQueryBuilder.php#L146-L154

p.s.: I didn't investigate further/tested.

**Comment by bozana** [comment]
@jonasraoni, why do you think that the left join could fail? :thinking:

**Comment by jonasraoni** [comment]
@bozana because the `where()` filter that I've highlighted will require at least one row to exist on the `edit_decisions` table, and that's not going to happen if the submission was approved without an editorial decision.
But as I said, I didn't test anything, I've just skimmed the code 🙂

**Comment by bozana** [comment]
Hmm... @jonasraoni, I think everything is OK. The query to get the accepted counts is:
```
select COUNT(DISTINCT s.submission_id) as count from `submissions` as `s` 
left join `publications` as `pi` on `pi`.`publication_id` = (select `pi2`.`publication_id` from
 `publications` as `pi2` where `pi2`.`submission_id` = `s`.`submission_id` and `pi2`.`status` = 3 order by `pi2`.`date_published` asc limit 1) 
left join `edit_decisions` as `ed` on `s`.`submission_id` = `ed`.`submission_id` 
 where `s`.`context_id` in (1) and `s`.`submission_progress` = 0 and (`pi`.`date_published` is null or CAST(s.date_
submitted AS DATE) <= pi.date_published) and `ed`.`decision` in (2, 17, 7) and `ed`.`date_decided` >= 2023-07-03 and `ed`.`date_decided` < 2023-10-02 and `s`.`status` != 4
```
Thus, if there is no editorial decision for a submission, it will be excluded by `left join edit_decisions as ed on s.submission_id = ed.submission_id`. The submissions that have an editorial decision will be further filtered by `where` clause, e.g. by the accept decision (Decision::ACCEPT, Decision::SKIP_EXTERNAL_REVIEW,       Decision::SEND_TO_PRODUCTION) and the decision date.
The accepted submissions should always have an entry in the table `edit_decisions`, having either decision = Decision::ACCEPT or Decision::SKIP_EXTERNAL_REVIEW or / and sometimes also Decision::SEND_TO_PRODUCTION. And they should always have `date_decided`.

**Review by jonasraoni — APPROVED** [review]
@bozana, I've approved! I've mixed the lack of a review with the lack of a decision.

**Pull request merged**
