### PR TITLE
pkp#6340 Set secure flag to true

### PR DESCRIPTION
**Pull request by salmanm2003**
Hi @asmecher,
I have set the secure flag to `true` regarding your discussion with @fradeve.

### CODE REVIEW

**Comment by fradeve** [comment]
@asmecher if the PR is acceptable, is there any chance that this can be included in a new release of OJS, e.g. `3.3.0-14`? That would be really helpful to deliver this to our customers.

**Comment by asmecher** [comment]
I think this will break cookies/sessions entirely for systems that are not delivering via `HTTPS`, no?

**Comment by salmanm2003** [comment]
@asmecher yes this won't work for HTTP websites, I will make the changes just for HTTPS and send a new PR?

**Comment by asmecher** [comment]
Please do, thanks.

**Comment by salmanm2003** [comment]
@asmecher could you check it now and let me know if any issues?

**Comment by asmecher** [comment]
@salmanm2003, what about the suggestion in the description of https://github.com/pkp/pkp-lib/issues/6340?
> Setting the [secure flag](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-secure) if a site has force_ssl enabled
This will guarantee we don't hit accidental side-effects due to e.g. proxy servers.

**Comment by salmanm2003** [comment]
@asmecher the script will check `force_ssl` config var value before turning the `secure` flag to true.

**Comment by asmecher** [comment]
@salmanm2003, if you rely on the `force_ssl` option, then I don't think it's necessary to check `$_SERVER['HTTPS']` at all; you can simply replace the `false` in the `setcookie` call with `Config::getVar('security', 'force_ssl')`.

**Comment by salmanm2003** [comment]
@asmecher, `force_ssl` value has been added as you mentioned above.

**Comment by asmecher** [comment]
Thanks, @salmanm2003! On to testing...
- Have you tested this locally?
- Could you open up a pull request to the OJS repository with a submodule update for the `lib/pkp` submodule, in order to kick off automated testing using OJS? See https://docs.pkp.sfu.ca/dev/testing/en/continuous-integration#prepare-pull-requests-for-testing for details on how to do this.

**Comment by salmanm2003** [comment]
@asmecher 
- I have tested the changes above and all were working properly.
- I will open a PR to OJS to start an automated test.

**Comment by salmanm2003** [comment]
Here is the PR for OJS testing.
[https://github.com/pkp/ojs/pull/3698](url)

**Comment by asmecher** [comment]
Thanks, @salmanm2003! A couple suggestions for next time...
- I'd suggest using feature branches rather than hacking on your `main` directly
- I was able to squash and merge this into a single commit in Github directly, but the team uses `git rebase -i` pretty heavily to maintain a clean commit history. This makes things like cherry-picks between branches a lot easier.

**Comment by salmanm2003** [comment]
@asmecher no problem, thanks for letting me know.

**Pull request merged**
