### PR TITLE
Syntax error on SQL for PostgreSQL on Submission searching

### PR DESCRIPTION
**Pull request by eniocarboni**
Syntax error on SQL for PostgreSQL on Submission searching: see issue #4599

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @eniocarboni! @NateWr, would you mind taking a look at this? Best to avoid `as` as a table alias.

**Comment by NateWr** [comment]
This looks good, thanks @eniocarboni!

@asmecher this also needs to be cherry-picked to master. Would you like me to merge and cherry-pick or are you happy doing that?

@eniocarboni for my own education, can you describe under what conditions I should be using `Capsule::getQueryGrammar()->wrap("ss.setting_value")`? From the docs I found, it looked to be related to ensuring compatibility between sql variants. But it's not clear to me in what way the `ss.setting_value` syntax would be incompatible.

**Comment by NateWr** [comment]
@eniocarboni never mind on my last question! I have just read the issue and now I understand. :)

**Comment by asmecher** [comment]
@eniocarboni, I'm not sure how you feel about this, but I would rather we *didn't* wrap names unless it was necessary. I find it makes the SQL a lot harder to read, and unless we apply changes like this everywhere (which would be very verbose), it'll be inconsistent.

**Comment by eniocarboni** [comment]
@asmecher, Ok I understand.

**Comment by asmecher** [comment]
I've made this change but without the extra wrappers (renaming `as` alias to `aus`): https://github.com/pkp/pkp-lib/commit/cdc81fa1ad34034a1f76d6d0e500dd8add86cb2e

**Pull request closed without merging**
