### PR TITLE
pkp/pkp-lib#2367: Add proxy support to ReCaptcha form validator.

### PR DESCRIPTION
**Pull request by ctgraham**
Should resolve pkp/pkp-lib#2367.  Linted only; I don't have a proxied instance for testing.

### CODE REVIEW

**Comment by ptrckb** [comment]
@ctgraham, I had to insert parentheses around the ternary operator of line 77. Otherwise the 'proxy' string is wrong with only ':PORT' or empty.

```
$ php -v
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
[...]
$ php -a
Interactive mode enabled

php > $x = 'A' . (true) ? 'B' : 'B';
php > echo $x, PHP_EOL;
B
php > $x = 'A' . ((true) ? 'B' : 'B');
php > echo $x, PHP_EOL;
AB
php > 
```

**Comment by ctgraham** [comment]
Thanks, @ptrckb .  I've replaced this commit.

**Comment by ptrckb** [comment]
It is OK now, thanks.

**Comment by asmecher** [comment]
Thanks, @ctgraham and @ptrckb! Merged.

**Pull request merged**
