### PR TITLE
Open review enhancements for 3.1.1

### PR DESCRIPTION
**Pull request by ajnyga**
This is a 3.1.1 compatible version of https://github.com/pkp/pkp-lib/pull/3077

@NateWr @asmecher 

Nate, I had problems with the new authorization code in PKPReviewerGridHandler and ended up doing this: https://github.com/pkp/pkp-lib/pull/3548/files#diff-9fdb2e615d5990a8febe174026523453R127 in the custom reviewer grid I am showing for the authors. The additions you made are connected to the editor as author logic, right? While the grid I made only shows open reviewers, I do not think the logic is needed there so I ended up bypassing it altogether - but is that the correct way of doing it?

Still missing the reviewers from the discussions participants list, but adding that soon. There are so many ifs and checks there to take into account all special cases. I am adding an extra logic where I check if the editor is also the author and if she is, hide the blind.

### CODE REVIEW

**Comment by NateWr** [comment]
Apologies, I probably won't get a chance to look at this until some time next week.

**Comment by ajnyga** [comment]
@NateWr 
I now added the support for your new userListQueryBuilder implementation when listing query participants. 

I know that you mentioned as a last comment here https://github.com/pkp/pkp-lib/pull/3077#issuecomment-363111714 that I should tamper with the array when `queryParticipantsListData` is returned. 

Well that turned into some really ugly coding, because it is not only about adding extra users to the list but you also need to remove some of them, like authors if the current user is a blind reviewer. 

So instead I followed your comment here https://github.com/pkp/pkp-lib/pull/3077#issuecomment-363101655 and introduced two new parameteres. `includeUsers `and `excludeUsers`. These are arrays that you can use to pass extra user_id's to add or remove users that you need besides the actual query you are doing.

 I used these both for always including the current editor in the discussion participants, even if the editor is not assigned to the submisision (https://github.com/pkp/pkp-lib/issues/3508) and also for manipulating the list in the review stage to include/exclude certain reviewers or authors from the list. Take a look what you think. This was so much cleaner solution that manipulating the array later on.

**Comment by ajnyga** [comment]
Also @NateWr 
Concerning the situation where the editor is also the author, I think that we should block access to the whole discussion feature. I could of course add a rule that when editor is also author, then do not show reviewer names in the query participants list, but you would still have all the discussions made by other editors and there the reviewer name could be in the text of the query. So just blocking the whole discussion section in review stage would be an easy and efficient way of handling this.

**Comment by ajnyga** [comment]
@asmecher the grid is now moved to the bottom.

Check the comments here https://github.com/pkp/pkp-lib/pull/3548#issue-179084320 and https://github.com/pkp/pkp-lib/pull/3548#issuecomment-381525698. The latter solution is maybe something @NateWr wants to comment? It seems to work ok.

**Comment by NateWr** [comment]
>  introduced two new parameteres. includeUsersand excludeUsers

That looks great, and now we have a general tool we can use elsewhere when we need it! :+1:

**Comment by asmecher** [comment]
Oh, one more request: could you reword your commits to prefix them with the issue number? e.g.:

    pkp/pkp-lib#2976 Description goes here

I normally do this with an interactive rebase (and feel free to squash commits if it makes sense to shorten the list).

**Comment by ajnyga** [comment]
Thanks, I will try. Never done that before but we will see what happens :rofl: 

I take it that the solution mentioned here is ok https://github.com/pkp/pkp-lib/pull/3548#issue-179084320?

**Comment by ajnyga** [comment]
@asmecher 
- comments are changed to // and years are now all 2018
- commits are reworded and some of them squashed (that was interesting)

@NateWr 
- I added the authorization check you suggested above
- prevented authors opening blind review reports with https://github.com/pkp/pkp-lib/pull/3548/files#diff-9fdb2e615d5990a8febe174026523453R158 (you were absolutely right!)

**Comment by ajnyga** [comment]
You are right. I will do a `OpenReviewAssignmentRequiredPolicy`, maybe it becomes handy in other places as well.

**Comment by ajnyga** [comment]
Hi @NateWr 

I added an extra parameter to `ReviewAssignmentRequiredPolicy` https://github.com/pkp/pkp-lib/pull/3548/commits/cc72a4360772c5af4a94c58b1dca071453c9773c

However, there is one thing I can not get to work. For some reason the SUBMISSION_REVIEW_METHOD_OPEN constant is not available in AuthorReviewerGridHandler.inc.php. I keep getting `Use of undefined constant SUBMISSION_REVIEW_METHOD_OPEN`

What is the catch here?

**Comment by NateWr** [comment]
You may need to import `ReviewAssignment.inc.php` if it hasn't yet been loaded (assuming that's where you've stored the new constant).

**Comment by ajnyga** [comment]
Thanks, I will try importing ReviewAssignmen.inc.php.

The SUBMISSION_REVIEW_METHOD_OPEN constant is not new, but already in use. This is actually the first time a core constant is not working inside another file. I was under the impression that this could not happen, but was apparently wrong...

**Comment by ajnyga** [comment]
Ok, so I need to do some changes now that https://github.com/pkp/pkp-lib/pull/3649 was merged...

**Comment by ajnyga** [comment]
@asmecher pinging you again regarding the code review/merge (because you encouraged me to do so a few weeks ago if I do not hear from you :D)

**Comment by asmecher** [comment]
@ajnyga, it worked :) sorry, this has been near the top of my list for a long time but new things kept getting added above it. I'm just running through some local testing in prep for cherry-picking over to `ojs-stable-3_1_1` -- but it's merged for `master` now, many thanks!

**Comment by asmecher** [comment]
And merged and tested for `omp-stable-3_1_1` / `ojs-stable-3_1_1` to boot!

**Pull request merged**
