### PR TITLE
Updated OAI stylesheet

### PR DESCRIPTION
**Pull request by jonasraoni**

### CODE REVIEW

**Comment by jonasraoni** [comment]
@Vitaliy-1 as Alec is away, let me know if you're ok to review this. It's just an update to the OAI stylesheet, it's maintained by the [same entity](https://github.com/eprints/eprints3.4/blob/master/lib/static/oai2.xsl), so it should be safe.

**Comment by jonasraoni** [comment]
@asmecher, here I'm just applying updates from upstream regarding the OAI stylesheet. If there's nothing against, I'll update the other branches.

**Comment by asmecher** [comment]
@jonasraoni, sure, no objections.

**Comment by asmecher** [comment]
@jonasraoni, I think this is ready for closing?

**Pull request merged**
