### PR TITLE
[Spanish translation] The word 'Preferencias' doesn't have diacritic

### PR DESCRIPTION
**Pull request by jorgesumle**

### CODE REVIEW

**Comment by marcbria** [comment]
First look over those files. This week Jordi will make a second review.
@mtub we made changes with comments, as far as we don't have write permissions over the files.
It means more mechanic work for you and more chances to introduce errors. 
Let's talks about this by mail?

**Comment by mtub** [comment]
@marcbria , can I merge this? Looks okay to me.

**Comment by mtub** [comment]
#2725

**Comment by marcbria** [comment]
Yes, you can. :-D

**Pull request merged**
