### PR TITLE
pkp/pkp-lib#1862 Compile unique template files for each context

### PR DESCRIPTION
**Pull request by NateWr**
@asmecher This stores unique template files for each context (+ a set for the overall site context). I'm wondering now if I should do it per theme instead. Thoughts?

### CODE REVIEW

**Comment by asmecher** [comment]
Hmm, yes, I think per theme would be a better match -- otherwise there will be an explosion of template files. These are small but there are already lots of them.

**Comment by NateWr** [comment]
Ok, I've updated it to use the `themePluginPath` for the current context or site.

**Comment by asmecher** [comment]
That breaks the installer -- you'll need to check the `installed` state so that this doesn't try to access the database before it's created.

**Comment by NateWr** [comment]
Good catch. I've updated this so that the overall site templates have no theme-specific prefix. This way they won't check the database and the overall site can only have one theme active at a time anyway.

**Pull request merged**
