### PR TITLE
pkp/pkp-lib#1397 consolidate settings

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by asmecher** [comment]
It looks like this orphans e.g. the sponsor and contributor grids as unused code.

**Comment by NateWr** [comment]
Yes it does. Shall I go ahead and remove those grids?

**Comment by NateWr** [comment]
Ok, I removed the sponsor and contributor grids too.

**Comment by asmecher** [comment]
Superseded by https://github.com/pkp/pkp-lib/pull/1463

**Pull request closed without merging**
