### PR TITLE
Do not remove numbers from the beginning of each citation:

### PR DESCRIPTION
**Pull request by GaziYucel**
* https://github.com/pkp/pkp-lib/issues/9946
* https://forum.pkp.sfu.ca/t/if-a-reference-list-item-starts-with-a-numeral-it-is-removed-3-1-2-4-and-3-3-0-15

### CODE REVIEW

**Comment by bozana** [comment]
Hi @GaziYucel, 

Would you maybe like to also provide the submodule update PRs (pointing to these changes) for OJS, OMP and OPS? -- We need them in order for the tests to be run, but also for stable branches, so that the user can update properly/accordingly.
If it is too much for you, I can do this -- I would take your commit and add the submodule updates. Just let me know please.
Thanks a lot!

**Comment by GaziYucel** [comment]
Hi @bozana,
Can you please do this for this PR. I have never done that before, I will find out how and will do this for my next PRs. 
Thanks.

**Comment by GaziYucel** [comment]
Hi @bozana, another question. I did this now for version 3.3.0. Shall I do this also for the versions 3.4.0 and 3.5.0? There is no corresponding issue for these.

**Comment by bozana** [comment]
Hi @GaziYucel, I will then cherry-pick it to the other branches now. Else, yes please, always for all higher/newer branches as well :-)
Thanks a lot!

**Comment by jonasraoni** [comment]
Closing as it was cherry-picked.

**Pull request closed without merging**
