### PR TITLE
Clean code with PhpStorm

### PR DESCRIPTION
**Pull request by stweil**
PhpStorm added some missing semicolons and removed wrong semicolons.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @stweil -- could you remove the change to `js/lib/jquery/plugins/jquery.form.js`? That's third-party code and we're trying desperately not to include *any* modifications to third-party code in our tree.

**Comment by stweil** [comment]
I removed that file now from the pull request.

**Comment by stweil** [comment]
@asmecher, the pull request should now be ready to get merged.

**Comment by asmecher** [comment]
Merged, thanks!

**Pull request merged**
