### PR TITLE
Translation es_ES Omp stable 3 1 1

### PR DESCRIPTION
**Pull request by gurumelo**
Completing

### CODE REVIEW

**Comment by mtub** [comment]
@marcbria, do you mind having a look?

**Comment by marcbria** [comment]
Translations reviewed. I added comments with corrections that need to be fixed before commit to the official release.
Sorry, @gurumelo for commenting instead of editing directly. 
I can't edit in github. We are looking for a better tool to manage translations.

Please @gurumelo make the changes suggested so @mtub can merge.

**Comment by mtub** [comment]
@gurumelo, do you still want to update this PR? Happy to help with any problems…

**Comment by gurumelo** [comment]
@marcbria Thanks, where are your corrections?
Gracias, dónde están las correcciones para poder hacer lo que me indicáis?

**Comment by gurumelo** [comment]
@mtub ping

**Comment by mtub** [comment]
@marcbria, I can't see any comments you have made.

**Comment by marcbria** [comment]
Nor do I... Looks like I mixed threads. :dancer: 

I reviewed @gurumelo changes and look great so merge please.

@mtub as far as we got weblate running and we finish OJS 3 ca_ES, OMP needs a deep review.

**Pull request merged**
