### PR TITLE
Update locale user.xml pt_BR

### PR DESCRIPTION
**Pull request by wundo**
This PR adds a missing translation and fixes some incorrect translations for pt_BR locale.

### CODE REVIEW

**Comment by wundo** [comment]
I think this is somewhat related with #2604

**Comment by wundo** [comment]
@mtub I wasn't sure how to approach this, several translations translate `Simon Fraser University` to the local language, maybe we should standardize this across translations.

Let me know if you want that I submit a pull request for that as well.

**Comment by wundo** [comment]
@mtub I've updated the PR based on your review.

**Comment by mtub** [comment]
Thank you, I think it is better this way. Probably wouldn't mind adding another organization, but renaming an existing organization is not such a good way. Keeping the original name is my favorite, so thank you :)

**Pull request merged**
