### PR TITLE
pkp/pkp-lib#602 Fix datepicker style and function

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by asmecher** [comment]
Nate, this one needs a rebase. Is this forked from master after last night?

**Comment by NateWr** [comment]
Should be forked from the master right after you merged my big branch. I'll take a look.

**Comment by NateWr** [comment]
I fear I may have just made things worse...

**Comment by asmecher** [comment]
Actually, that looks fine to me (looking at the "files changed" branch); I suspect you're unhappy about the merge commit. If you do a...

    git rebase -i official/master

...it should clean things up. Let me know if you want me to step you through this; it's a simple example and interactive rebase is really handy for keeping commit histories clean.

**Comment by asmecher** [comment]
Merged, thanks!

**Pull request merged**
