### PR TITLE
wrong Spanish translate

### PR DESCRIPTION
**Pull request by t4x0n**
the translate was not correct and for space this can't say "Enviar correo electrónico al revisor"

@marcbria la traducción no era correcta y por el espacio disponible no puede decir "Enviar correo electrónico al revisor"

### CODE REVIEW

**Comment by asmecher** [comment]
@marcbria, shall I merge this?

**Comment by marcbria** [comment]
Not yet. 
@t4x0n is right (we need a change), but should be replaced by "Enviar correo al revisor".
I don't mind to modify directly but I can't change it myself. :-(

**Comment by t4x0n** [comment]
thanks @marcbria, I modified the patch, so now is ok to merge it @asmecher

**Comment by marcbria** [comment]
Thanks @t4x0n 
@asmecher you can merge now if you like.
Thanks.

**Comment by asmecher** [comment]
Merged and cherry-picked, thanks!

**Pull request merged**
