### PR TITLE
Adding support for server-side SASS compilation

### PR DESCRIPTION
**Pull request by Vitaliy-1**
I'm using here scssphp compiler for SCSS written in PHP. It is distributed under MIT license. 
I have tested this code on my local machine and hoping that didn't forget something.

### CODE REVIEW

**Comment by Vitaliy-1** [comment]
#3449

**Comment by asmecher** [comment]
@NateWr, any opinions on SASS vs. LESS?

**Comment by NateWr** [comment]
SASS is definitely more popular than LESS, though they do much the same thing. Does it bother you to ship both compilers? As a backend developer my instinct is to pick one and stick with it. But as a themer I can see the benefits of our platform having native support for both.

If it doesn't bother you shipping both composer dependencies, having support for SASS and LESS would be a nice developer feature.

If this goes forward, one thing I might want to revisit is our ThemeAPI handling of modifying LESS variables at run time. The naming patterns are built around the expectation that we're injecting LESS (see [modifyStyle](https://pkp.gitbooks.io/pkp-theming-guide/content/en/theme-api.html)). Perhaps those should be renamed. 

@Vitaliy-1 does SASS work the same as LESS, where you can override a LESS variable at any time and it overrides it globally?

**Comment by Vitaliy-1** [comment]
Hi @NateWr 
Yep, the last defined variable with the same name wins (throughout the compiled imports). But you can prevent it by using `!default` specifier; it means "use this variable value if it is not defined before".

**Pull request closed without merging**
