### PR TITLE
pkp/pkp-lib#5964 Adds a new notification for when a new version of a submission is created

### PR DESCRIPTION
**Pull request by JhonathanLepidus**
We are sending this PR so it can be present in 3.2.1-x and other 3.2.x future releases. This can be helpful for people until a 3.3 release arrives.

### CODE REVIEW

**Comment by asmecher** [comment]
@JhonathanLepidus, this looks very clean! Could you fill out a matching [github issue](https://github.com/pkp/pkp-lib/issues/new?assignees=&labels=&template=feature_request.md&title=Create+a+notification+when+a+new+version+is+created) (if there isn't one already)? I'd like to discuss delivery there too, specifically...

- Who should receive the notification? Currently (from this PR) it looks like all managerial roles assigned to the journal/press/server, but I think it might better be sent to editorial users assigned to the current submission. Plus, we might consider other people, e.g. authors, if that's desirable.

Link to this PR from the new issue entry so everything is kept together.

We're likely going to release OJS 3.2.1 tomorrow, so this probably won't make it in, but as you've noted it'll be ready for users who need to patch it while we're working on the next release.

Thanks!

**Comment by diegoabadan** [comment]
Alec, is related to this issue:
https://github.com/pkp/pkp-lib/issues/5964

Our wish is not to need to apply the patch now, then 3.2.1, then 3.2.1-1 etc. So, if we can have it before 3.3 it would be nice, even if I can't get into tomorrow's launch specifically.

**Comment by asmecher** [comment]
Thanks, @diegoabadan, it looks like I closed that one accidentally.

**Comment by diegoabadan** [comment]
Thanks, @asmecher !

**Comment by asmecher** [comment]
Cherry-picked the last commit to `master` -- thanks, @JhonathanLepidus!

**Pull request merged**
