### PR TITLE
pkp/pkp-lib#4503 updated nl_NL locale

### PR DESCRIPTION
**Pull request by rvdb**
NOTE: following plugins have been skipped, for which no en_US reference locale is present:
  - pkp-lib/plugins/citationLookup/crossref
  - pkp-lib/plugins/citationLookup/isbndb
  - pkp-lib/plugins/citationLookup/pubmed
  - pkp-lib/plugins/citationLookup/worldcat
  - pkp-lib/plugins/citationParser/freecite
  - pkp-lib/plugins/citationParser/paracite
  - pkp-lib/plugins/citationParser/parscit
  - pkp-lib/plugins/citationParser/regex
  - pkp-lib/plugins/metadata/nlm30

### CODE REVIEW

**Comment by rvdb** [comment]
Sorry, reworking against latest `stable-3_1_2`. Probably ready quite soon.

**Comment by mtub** [comment]
@rvdb, your are providing commits by other users. Could you rework this so that you only add your locale files? (You could create a new branch and cherry-pick your commits from this branch if you don't want to start from scratch…)

**Comment by rvdb** [comment]
Ok, done (at least, https://github.com/pkp/pkp-lib/pull/4521/commits/c914486cff4cb9c8ad4813da756cc8754aec2e39 was what I intended; don't know what's with the other commits).

**Comment by rvdb** [comment]
Sorry @mtub , I've been fighting my day through Git and fed up with it. I intended to only commit my stuff, but apparently everything else came along. I'll try to cherry-pick and hope to get this out of my system quickly.

**Comment by mtub** [comment]
@rvdb , I can sort this out for you, just tell me to do it :-)

**Comment by rvdb** [comment]
@mtub if it is not too much of a hassle for you, Please Do (and make my day :-) )!

**Comment by mtub** [comment]
will do! THanks for your hard work and your willingness to do this via GitHub. Much appreciated!

**Comment by asmecher** [comment]
@rvdb, thanks from me as well for all this work! Just FYI, the most common cause of other commits getting pulled in by accident is opening the pull request against the wrong branch.

**Comment by mtub** [comment]
superseded by #4525

**Pull request closed without merging**
