### PR TITLE
Check phpunit version for RouterTest

### PR DESCRIPTION
**Pull request by withanage**

### CODE REVIEW

**Comment by withanage** [comment]
Hi @asmecher ,

This PR chcecks for phpunit version for  version 3.3 , php errors

**Comment by withanage** [comment]
#### Related
- https://github.com/pkp/ops/pull/695
- https://github.com/pkp/ops/pull/695

**Review by asmecher — COMMENTED** [review]
Since we specify the phpunit version in Composer, I don't think we need to support multiple versions.

**Comment by withanage** [comment]
@asmecher  thanks! closing without merged,  cause it can be solved  by setting php ini values explicitly for phpunit

**Pull request closed without merging**
