### PR TITLE
Update admin.xml

### PR DESCRIPTION
**Pull request by alonsoj**

### CODE REVIEW

**Comment by beghelli** [comment]
Thanks @alonsoj .

@mtub can I merge?

**Comment by mtub** [comment]
Hi @beghelli , I like to have another review - if you don't mind I'll take over.

**Comment by marcbria** [comment]
Are those literals missed in the last OJS es_ES translation we delivered? Thanks @alonsoj to make us notice.
Look good to me but I can't garantee they are following our translation style guide... 
Could we use them as temporary till our linguist take a look to them (for instance when reviewing missing chains in the OJS translation module)?

**Comment by mtub** [comment]
What do you mean be "use them as temporary" - can you keep track of these changes yourself and have your experts have another look when they start working on OJS again? Because I'd like to merge these, and after that, it's up to you to remember contributions made by other contributors…

**Comment by mtub** [comment]
Sorry, I can't merge this - this is a pull request for ojs-dev-2_4, but the added lines seem to come from the master branch. es_ES locale is complete for ojs-dev-2_4. @marcbria, maybe you can have a look at these suggestions when completing the master branch translation.

**Comment by mtub** [comment]
Sorry, my fault - re-opened, will check again.

**Pull request closed without merging**
