### PR TITLE
add and order keys, and others little changes Spanish submission.xml

### PR DESCRIPTION
**Pull request by t4x0n**
ordené gran parte del archivo de acuerdo al original en inglés y agregué las keys faltantes más importantes @marcbria

### CODE REVIEW

**Comment by marcbria** [comment]
Hola Carlos,

Did you get the translation guide and the glossary?
File sent to the translator.

Cheers,
m.

**Comment by t4x0n** [comment]
Yes @marcbria, now I see your email, and go to reply! Later I go to check the guide and review the changes I submitted. Thank you!

**Comment by t4x0n** [comment]
@marcbria I send you a second email with some questions for improving my translation

**Comment by marcbria** [comment]
Got it. Let's talk by mail.

**Comment by mtub** [comment]
HI @marcbria, is this part of your newer PRs and can I close this issue?

**Comment by t4x0n** [comment]
this is obsolete now! I am closing this PR

**Pull request closed without merging**
