### PR TITLE
Change workflow buttons

### PR DESCRIPTION
**Pull request by NateWr**
This removes the Expedite Submission functionality and changes the Accept Submission button to Send to Copyediting (it also removes the highlighted color on it).

A PR for OMP is coming and OJS is prepared (see https://github.com/NateWr/ojs/tree/change_workflow_buttons). However, it looks like some of our tests in OJS use the expedite feature:

https://github.com/pkp/ojs/blob/master/tests/data/60-content/BvemerSubmissionTest.php#L41
https://github.com/pkp/ojs/blob/master/tests/data/60-content/JforchtSubmissionTest.php#L40
https://github.com/pkp/ojs/blob/master/tests/data/60-content/KbaumanSubmissionTest.php#L40
https://github.com/pkp/ojs/blob/master/tests/data/60-content/NpiersonSubmissionTest.php#L40
https://github.com/pkp/ojs/blob/master/tests/data/60-content/RcerpaSubmissionTest.php#L41
https://github.com/pkp/ojs/blob/master/tests/data/60-content/RyagnaSubmissionTest.php#L40

And in the Lens Galley plugin:

https://github.com/asmecher/lensGalley/blob/master/tests/functional/LensFunctionalTest.php#L83

Not sure what we want to do with this. I guess we have to shepherd them through the publishing process, but I'm not sure I could pull this off unless I set up the tests locally.

### CODE REVIEW

**Comment by NateWr** [comment]
OMP PR: https://github.com/pkp/omp/pull/212

**Comment by asmecher** [comment]
@NateWr, I think a better approach than duplicating a lot of workflow testing for these would be to change them into import/export tests for the native XML plugin. Much faster, and we'd gain coverage for that part of the system, which isn't tested yet. I'll see if I can spend some time on that tomorrow.

**Comment by asmecher** [comment]
I converted the expedited submission tests in tests/data over to XML import instead. Lens reader is next.

**Comment by asmecher** [comment]
Lens test conversion: https://github.com/asmecher/lensGalley/commit/11e813035113f1b8be6c11bd9d48b62955746849
Issue 1 Vol 1 test conversion: https://github.com/pkp/ojs/commit/ec9cffc8c5f688a85aea4927293b65f155642088

**Comment by NateWr** [comment]
Thanks @asmecher. I've just issued a PR for OJS as well, so they are at:

OMP: https://github.com/pkp/omp/pull/212
OJS: https://github.com/pkp/ojs/pull/749

**Comment by asmecher** [comment]
Merged from my PR after a little rebasing & tinkering. Thanks, @NateWr!

**Pull request closed without merging**
