### PR TITLE
pkp/pkp-lib#4273: add breadcrumbs in custom pages

### PR DESCRIPTION
**Pull request by ctgraham**
Addresses custom NMI pages in default theme for #4273.

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks @ctgraham. I think the goal was to include both breadcrumbs _and_ page title, as shown in the last image here: https://github.com/pkp/pkp-lib/issues/4273#issuecomment-443692851.

However, as you probably noticed, including both will result in two `<h1>` elements on the page. To do this, we need to update the `breadcrumbs.tpl` file to accept a `$noHeading` variable that we can pass to it, like this:

```
{include file="frontend/components/breadcrumbs.tpl" currentTitle=$title noHeading=true}
```

Then in `breadcrumbs.tpl` do something like this:

```
{if $noHeading}<span class=">{else}<h1>{/if}
```

And then the CSS styles may need to be updated, I'm not sure.

**Comment by asmecher** [comment]
@NateWr, any objections to this one?

**Comment by NateWr** [comment]
No, it's not ready yet, see our comments here: https://github.com/pkp/pkp-lib/issues/4273#issuecomment-539083628

**Comment by ctgraham** [comment]
@NateWr describes this as being already merged to master and stable here:
https://github.com/pkp/pkp-lib/issues/4273#issuecomment-549444323

So I think we can close this.

**Pull request closed without merging**
