### PR TITLE
Updates in the Arabic locale to match those in the English version

### PR DESCRIPTION
**Pull request by vormia**
After the release of OJS ver. 2.4.7, some locale files were updated in
the English Language by adding several keys here and there, so the
Arabic version should be updated as well.
I made a brief revision to the styles used in the system, and found that
some adjustments were necessary to have a better experience to the
Arabic user. I added the (div) tag there because the right-to-left
orientation in the (body) tag wasn't enough to satisfy the required
page content view.

### CODE REVIEW

**Comment by mtub** [comment]
Hi @vormia , thanks for the update. I am not so sure about the changes to rtl.css, though:

a) The css file could be used for right-to-left languages not using Arabic fonts, so modifying rtl.css to use an Arabic font might be confusing
b) Is it necessary to modify all the styles individually?

Maybe renaming copying rtl.css to something like rtl-arabic.css might be useful. @asmecher, do you have some guidance for us?

**Comment by vormia** [comment]
Hi @mtub, the renaming you suggested for *rtl.css* file is convenient.
This is what happened:
When OJS 2.4.7 was released, I installed the system locally to give it a try, especially, to figure out how the **Arabic interface** would appear. Typical fonts used in the *common.css* file had some minor **problem** displaying 'diacritical marks' which are used widely in Arabic. Sometimes the word meaning changes according to those diacritics, rather than to appear as a misspelling.
Since I had used these marks in the Arabic text, I had to choose **another font** that displays 'diacritical marks' properly, and on the other hand **resides** habitually in the Arabic user local environment.
When this font was implemented, the scripts on mostly every page appeared very small, and required **enlargement** every time the user visits the site, which doesn't give him a good expression about the system. It is well known to us here that **English** texts could endure shrinking to smaller sizes than the **Arabic** texts, due to some facts about the Arabic Language figures, which use *dots* or say *points* in many letters, and implementing *diacritical marks*... and some other reasons.
However, I couldn't put my hand on some other css files, like 'tinymace' which were used in the new *textarea* that appeared in this new release. Arabic letters there are quite small.

By the way, this pull request concerns PKP-library. I would have another one soon regarding OJS repository to match up updates that came with OJS 2.4.7.
Many thanks.

**Comment by NateWr** [comment]
@asmecher FYI, a similar issue will need to be solved for OJS 3.0. The Noto Sans font supports many languages, but we don't load them all at once to save on file size. We'll want to be able to modify the font based on locale. And we'll probably want some way to define and import locale-specific LESS files  into the compilation where we can modify the variables and define new rules.

**Comment by asmecher** [comment]
Hi all -- thanks for the conversation --

@NateWr, there's support in the system for specifying a `.css` file in `registry/locales.xml` for each locale file. I don't think it's necessary to support `.less` compilation here, as we'll likely have a few styles for a small subset of locales, rather than a complex tree.

@vormia and @mtub, please go ahead with the renamed file. Thanks for contributing!

**Comment by mtub** [comment]
All right. @vormia, could you please

* reset `rtl.css` to the original state and copy your modifications to a new `rtl-arabic.css` file (in `lib/pkp/styles/`)
* for your modifications in OJS use the same `rtl-arabic.css` file 
* change the path to the css file in `registry/locales.xml` from `lib/pkp/styles/rtl.css` to `lib/pkp/styles/rtl-arabic.css`

You could also try and see if you really need to add the font in so many contexts - but the CSS isn't pretty as it is, so that's not really urgent.

Please update your pull request, I will have another look then. Thanks!

**Comment by vormia** [comment]
OK, @mtub , I think I'm done here. I kept ```rtl.css``` to play the role of _right-to-left_ orientation changer, and added another file named ```rtl-arabic.css``` to customize the fonts used for **Arabic** locale.
Soon, a pull request would be requested for OJS library.

**Comment by NateWr** [comment]
Late response, but @asmecher the `registry/locales.xml` solution sounds good.

**Comment by mtub** [comment]
Thanks, @vormia . Will merge now and then update `registry\locales.xml` so that the ar_IQ locale uses your new rtl-arabic.css.

**Comment by vormia** [comment]
Thanks @mtub,
I would check periodically for any changes in English local files to make sure the Arabic ones are up-to-date.
That's all for now.

**Pull request merged**
